name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-cache
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - run: pnpm exec biome ci --error-on-warnings .
      - run: pnpm run check:css
      - run: pnpm run build

  test-unit:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu, macos]
        # Run on the most recently supported version of node for all bots.
        node: [20]
        include:
          # Additionally, run the oldest supported version on Ubuntu. We don't
          # need to run this on all platforms as we're only verifying we don't
          # call any APIs not available in this version.
          - runner: ubuntu
            node: 18.15.0 # Supported by VS Code 1.85.0 (November 2023).
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-cache
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.node }}-pnpm-store-
      - run: pnpm install
      - run: pnpm build
      - run: pnpm run test:unit

  test-integration:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu, macos]
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-cache
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - run: pnpm run build
      - run: xvfb-run -a pnpm -C client/vscode run test:integration
        if: matrix.runner == 'ubuntu'
      - run: pnpm -C client/vscode run test:integration
        if: github.ref == 'refs/heads/main' && (matrix.runner == 'windows' || matrix.runner == 'macos')
      - run: xvfb-run -a pnpm -C client/vscode run test:e2e
        # if: matrix.runner == 'ubuntu' # only run e2e tests on Linux
        if: false # no openctx logs printed so this fails for some reason on CI
