name: vscode-pre-release

on:
  schedule:
    - cron: '0 15 * * *' # daily at 1500 UTC
  workflow_dispatch:

jobs:
  release:
    if: github.ref == 'refs/heads/main' && github.repository == 'sourcegraph/openctx'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
        with:
          run_install: true
      - run: pnpm build
      - run: pnpm run test:unit
      - run: xvfb-run -a pnpm -C client/vscode run test:integration
      - run: RELEASE_TYPE=pre pnpm -C client/vscode run release
        if: github.ref == 'refs/heads/main' && github.repository == 'sourcegraph/openctx'
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          VSCODE_OPENVSX_TOKEN: ${{ secrets.VSCODE_OPENVSX_TOKEN }}
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@4e5fb42d249be6a45a298f3c9543b111b02f7907
        env:
          SLACK_CHANNEL: openctx
          SLACK_ICON: https://github.com/sourcegraph.png?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Pre-release build failed
          SLACK_COLOR: danger
          SLACK_FOOTER: ''
          MSG_MINIMAL: actions url
